@startuml

title __RESTAURANT's Class Diagram__\n

  namespace mindera.mindswap.aveiro.module1.intro.restaurant {
    class restaurant.mindera.mindswap.porto.module1.intro.Client {
        - tableNumber : int
        + askForTable()
        + order()
        + pay()
        + setRestaurant()
        - checkRestaurantPresence()
    }
  }
  

  namespace mindera.mindswap.aveiro.module1.intro.restaurant {
    class restaurant.mindera.mindswap.porto.module1.intro.Main {
        {static} + main()
    }
  }
  

  namespace mindera.mindswap.aveiro.module1.intro.restaurant {
    class restaurant.mindera.mindswap.porto.module1.intro.Restaurant {
        - c : Client[]
        - fullCapacity : boolean
        - numberOfOccupiedTables : int
        {static} - restaurantCount : int
        - tables : Table[]
        + Restaurant()
        + findTable()
        + freeTable()
        {static} + getRestaurantCount()
        + receiveOrder()
        - checkIfTableCanBeFreed()
        - occupyTable()
    }
  }
  

  namespace mindera.mindswap.aveiro.module1.intro.restaurant {
    class restaurant.mindera.mindswap.porto.module1.intro.Table {
        - free : boolean
        - order : String
        + Table()
        + cleanOrder()
        + getOrder()
        + isFree()
        + occupy()
        + saveOrder()
        + unoccupy()
    }
  }
  

  restaurant.mindera.mindswap.porto.module1.intro.Client o-- restaurant.mindera.mindswap.porto.module1.intro.Restaurant : restaurant


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
